export const GET_TOKEN = 'GET_TOKEN';
export const LOG_OUT = 'LOG_OUT';

export const FONT_LOADED = 'FONT_LOADED';
export const DATA_LOADING = 'DATA_LOADING';
export const DATA_LOADED = 'DATA_LOADED';
export const REVIEW_SELECTED = 'REVIEW_SELECTED';

export const RESTAURANT_SELECTED = 'RESTAURANT_SELECTED';
export const RESTAURANT_GET_MENU = 'RESTAURANT_GET_MENU';
export const CHANGE_CURRENT_CATEGORY = 'CHANGE_CURRENT_CATEGORY';
export const EDIT_MENU = 'EDIT_MENU';
export const GET_ORDER_AGAIN = 'GET_ORDER_AGAIN';
export const RESET_RESTAURANT_REDUCER = 'RESET_RESTAURANT_REDUCER';

export const GET_ORDER_ID = 'GET_ORDER_ID';
export const CLEAR_QUEUE = 'CLEAR_QUEUE';
