export const EMAIL_CHANGE = 'EMAIL_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GOTO_REGISTER = 'GOTO_REGISTER';
export const NAME_CHANGE = 'NAME_CHANGE';
export const PHONE_CHANGE = 'PHONE_CHANGE';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_FAIL = 'CREATE_FAIL';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CLEAR_STATE = 'CLEAR_STATE';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_REQUEST = 'FORGET_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const GET_TOKEN = 'GET_TOKEN';

export const FONT_LOADED = 'FONT_LOADED';
export const DATA_LOAD = 'DATA_LOAD';

export const RESTAURANT_SELECTED = 'RESTAURANT_SELECTED';
export const RESTAURANT_GET_MENU = 'RESTAURANT_GET_MENU';
export const CHANGE_CURRENT_CATEGORY = 'CHANGE_CURRENT_CATEGORY';
export const ADD_MENU = 'ADD_MENU';
export const SUB_MENU = 'SUB_MENU';
