# Generated by Django 2.1.2 on 2019-01-29 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20190129_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthday', models.DateField()),
                ('tel_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('profile_picture', models.ImageField(upload_to='account/customer/profile')),
            ],
        ),
    ]
