# Generated by Django 2.1.2 on 2019-04-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='account/customer/profile/default_user.png', upload_to='account/customer/profile'),
        ),
    ]
