# Generated by Django 2.1.2 on 2019-04-08 23:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20190407_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tel_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
