# Generated by Django 2.1.2 on 2019-03-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
