# Generated by Django 2.1.2 on 2019-03-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_promotion_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
