# Generated by Django 2.1.2 on 2019-04-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_promotion_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(default='default/no_picture.png', upload_to='promotion'),
        ),
    ]
