# Generated by Django 2.1.2 on 2019-03-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Waiting'), (2, 'Cooking'), (3, 'Done'), (4, 'Cancel'), (5, 'Success'), (6, 'Timeout')], default=0),
        ),
    ]
