# Generated by Django 2.1.2 on 2019-04-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190309_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Inprocess'), (2, 'DONE'), (3, 'CANCEL')], default=0),
        ),
    ]
