# Generated by Django 2.1.2 on 2019-04-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_donetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='donetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Inprocess'), (2, 'DONE'), (3, 'CANCEL'), (4, 'SUCCESS')], default=0),
        ),
    ]
