# Generated by Django 2.1.2 on 2019-04-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190418_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdaymenu',
            name='total',
        ),
    ]
