# Generated by Django 2.1.2 on 2019-01-29 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20190129_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='supplier/extra')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('image', models.ImageField(upload_to='supplier/menu')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.MainCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(upload_to='supplier/profile')),
                ('banner_picture', models.ImageField(upload_to='supplier/banner')),
                ('address', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('isopen', models.BooleanField(default=False, verbose_name='open status')),
                ('category', models.CharField(choices=[('FASTFOOD', 'อาหารจานด่วน'), ('BAKERY', 'เบเกอรี่'), ('CAFE', 'คาเฟ่'), ('STEAK', 'สเต็ก'), ('CHINESE', 'อาหารจีน'), ('KOREA', 'อาหารเกาหล่ี'), ('THAI', 'อาหารไทย'), ('INDIA', 'อาหารอินเดีย'), ('ITALY', 'อาหารอิตาลี่'), ('OTHER', 'อื่นๆ')], default='OTHER', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.SubCategory'),
        ),
        migrations.AddField(
            model_name='menu',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='extrapicture',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
    ]
