# Generated by Django 2.1.2 on 2019-02-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20190129_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='isopen',
            new_name='isOpen',
        ),
    ]
