# Generated by Django 2.1.2 on 2019-03-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20190313_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier/menu'),
        ),
    ]
