# Generated by Django 2.1.2 on 2019-03-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20190313_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
    ]
