# Generated by Django 2.1.2 on 2019-02-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20190204_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierQueueIndex',
            fields=[
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='supplier.Supplier')),
                ('category', models.CharField(default='A', max_length=1)),
                ('index', models.CharField(default='000', max_length=3)),
            ],
        ),
    ]
