# Generated by Django 2.1.2 on 2019-02-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplierqueueindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='supplier.Supplier'),
        ),
    ]
