# Generated by Django 2.1.2 on 2019-04-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_auto_20190406_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='supplier/menu/food_default.png', upload_to='supplier/menu'),
        ),
    ]
