# Generated by Django 2.1.2 on 2019-04-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20190406_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default/no_picture.png', upload_to='supplier/category'),
        ),
        migrations.AlterField(
            model_name='extrapicture',
            name='image',
            field=models.ImageField(default='default/no_picture.png', upload_to='supplier/extra'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='banner_picture',
            field=models.ImageField(default='default/no_picture.png', upload_to='supplier/banner'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='profile_picture',
            field=models.ImageField(default='default/no_picture.png', upload_to='supplier/profile'),
        ),
    ]
