# Generated by Django 2.1.2 on 2019-04-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_auto_20190407_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='longtitude',
            field=models.FloatField(default=0),
        ),
    ]
