# Generated by Django 2.1.2 on 2019-04-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_auto_20190407_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
