# Generated by Django 2.1.2 on 2019-04-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_auto_20190407_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='isOpen',
            new_name='is_open',
        ),
    ]
