# Generated by Django 2.1.2 on 2019-04-18 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0011_auto_20190408_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
